version: '3.8'

services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./api:/srv/api
    working_dir: /srv/api
    ports:
      - 8081:80
    entrypoint: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "80"]
    networks:
      - kanri_network
  db:
    container_name: db
    image: mysql:8.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=kanri_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - kanri_app_data:/var/lib/mysql
    networks:
      - kanri_network

volumes:
  kanri_app_data:

networks:
  kanri_network:
    external: true
