version: '3.8'

services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/srv/src
    working_dir: /srv/src
    ports:
      - 8081:80
    entrypoint: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "80"]
