version: '3.8'

services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./api:/srv/api
    working_dir: /srv/api
    ports:
      - 8081:80
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "80"]
    env_file:
      - ./.env.dev
    networks:
      - kanri_network
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:8.0
    volumes:
      - kanri_app_data:/var/lib/mysql
    env_file:
      - ./.env.dev
    networks:
      - kanri_network

volumes:
  kanri_app_data:

networks:
  kanri_network:
    external: true
