version: '3.8'

services:
  front:
    container_name: front
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./app:/srv/app
    working_dir: /srv/app
    ports:
      - 8080:5173
    # tty: true
    entrypoint: ["npm", "run", "dev"]
    networks:
      - kanri_network

networks:
  kanri_network:
