# FROM node:18.12.1-bullseye
FROM node:16.19-alpine

# ARG UID=1000
# ARG GID=1000
# ARG USERNAME=reacter
# ARG GROUPNAME=reacterG

# RUN groupadd -g ${GID} ${GROUPNAME} &&\
#   useradd -u ${UID} -G ${GROUPNAME} -s /bin/bash ${USERNAME}

USER node
